### ISSUE TITLE
How to avoid errors when chain of objects in field mapping contains nulls?

### ISSUE THREAD

**Issue by timurib** [fsi-open/datagrid#63]
Hello. 

First, thank you for this component, it is very useful!

I have a problem with a complex mapping paths. In some cases i need to show properties of related objects at the grid column. For example:

```
columns:
  foo_bar_baz:
    type: text
    options:
      field: [ foo.bar.baz ]
```

When there are `bar` contains a NULL, it will cause a DataMappingException that can not be catched and grid can not be built. Is there a way to supress this errors just to display the empty values?

The only way that I could find is overriding a class name of service `datagrid.data_mapper.chain` through the application parameters. But it's dirty, is there a better way?
