### ISSUE TITLE
Datagrid does not differentiate between a non-existant property and null

### ISSUE THREAD

**Issue by szymach** [fsi-open/datagrid#87]
The problem occurs when accessing fields of a an object, example:

```yaml
columns:
  name:
    type: text
    field: region.name
    options:
      field_mapping: ['region.name']
      label: admin.region.name
```
The `Region` does have a field called `name`, but if there is no object present (`getRegion()` yields a `null`), `DataGrid` tries to access the field on an empty value, thus throwing an exception that the field does not exist. It can be pretty confusing for one and does not allow for having an optional value for that field. Either all rows have an object for that field or an exception is thrown, which is far from ideal.

Current solution would be to put a `__toString()` method on the `Region` class instead of accessing the `name` property in `DataGrid`, but I do not think this is a sufficient solution.
